name: "OVOS Persona"
version: "0.0.10"
slug: "ovos_persona"
description: "Ollama-compatible OVOS persona server, usable as a Home Assistant conversation agent"
url: "https://github.com/andlo/haos-ovos-addons/tree/master/ovos-persona"
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
map:
  - share:rw
ports:
  8337/tcp: 8337
ports_description:
  8337/tcp: "Ollama/OpenAI-compatible API port"
options:
  solvers:
    - "ovos-solver-plugin-ddg"
    - "ovos-solver-failure-plugin"
  solver_config: '{"ovos-solver-bm25-freebase-plugin": {"enabled": false}, "ovos-solver-bm25-squad-plugin": {"enabled": false}, "ovos-solver-yes-no-plugin": {"enabled": false}, "ovos-solver-bus-plugin": {"enabled": false}, "ovos-chat-openai-plugin": {"enabled": false}}'
  extra_pip_packages: ""
  log_level: "info"
schema:
  solvers: ["str"]
  solver_config: "str"
  extra_pip_packages: "str"
  log_level: "list(debug|info|warning|error)"
