name: "OVOS Wyoming Wakeword"
version: "0.0.5"
slug: "ovos_wyoming_wakeword"
description: "Expose OVOS wake word plugins via Wyoming for use in Assist pipelines"
url: "https://github.com/andlo/haos-ovos-addons/tree/master/ovos-wyoming-wakeword"
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
map:
  - share:rw
ports:
  10400/tcp: 10400
ports_description:
  10400/tcp: "Wyoming protocol port"
discovery:
  - wyoming
options:
  hotwords_config: '{"hey_mycroft": {"module": "ovos-ww-plugin-precise-lite", "model": "https://github.com/OpenVoiceOS/precise-lite-models/raw/master/wakewords/en/hey_mycroft.tflite"}}'
  extra_pip_packages: ""
  zeroconf: true
  log_level: "info"
schema:
  hotwords_config: "str"
  extra_pip_packages: "str"
  zeroconf: "bool"
  log_level: "list(debug|info|warning|error)"
